import Link from 'next/link';
import { Metadata } from 'next';
import '../globals.css';
import { getPages } from '@/sanity/sanity-utils';

export const metadata: Metadata = {
  title: 'My awesome app',
  description: 'Generated by create next app + sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  //get all pages
  const pages = await getPages();
  return (
    <html lang="en">
      <body className='max-w-3xl mx-auto py-10'>
        <header className='flex items-center justify-between'>
          <Link href="/"
          className="bg-gradient-to-r from-orange-400 via-red-500 to-purple-600 bg-clip-text text-transparent text-lg font-bold">Marek</Link>

          <div className='flex items-center gap-5 text-small text-gray-600'>
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className='hover:underline'>
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className='py-20'>{children}</main>
        
        </body>
    </html>
  )
}
